{% set name = "ttim" %}
{% set version = "0.4" %}
#{% set sha256 = "2790663285e22e5a58dfe38f16166c0b09b610890205d98996fd0c72491cbb18" %}

package:
   name: {{ name|lower }}
   version: {{ version }}

source:
        #url: https://github.com/mbakker7/{{ name }}/archive/{{ version }}.tar.gz
        #sha256: {{ sha256 }}
        git_url: https://github.com/jentjr/ttim.git
        git_tag: ci_build_branch

build:
  number: 0
  skip: True  # [py<35]
  script: python setup.py install

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - python 
    - numpy >=1.12 
    - scipy
    - pandas
    - matplotlib >=2.0
  run:
   - python 
   - {{ pin_compatible('numpy') }} 
   - scipy
   - pandas
   - matplotlib >=2.0

test:
  imports:
    - ttim

about:
  home: https://github.com/mbakker7/ttim
  license: MIT
  license_file: LICENSE
  summary: 'ttim is a transient multi-layer analytic element model'
  dev_url: https://github.com/mbakker7/ttim
  
extra:
  recipe-maintainers:
    - mbakker7
    - jentjr
